% model_summary - the vintage numbers in MODELS.md, computed from a release.
%
%   rows = model_summary(csvdir)
%   rows = model_summary(csvdir, docfile)
%
% csvdir holds the tidy CSVs a release publishes. Returns one row per model with
% its last quarter, posterior mean, 90 percent band width and the variability of
% the series. Given docfile, the block between the two markers is rewritten, so
% the guide quotes the release rather than numbers typed in by hand.
%
% The markers must both be present and in order, since a silent no-op would leave
% the guide quoting an older vintage.

function rows = model_summary(csvdir, docfile)

arguments
    csvdir {mustBeTextScalar}
    docfile {mustBeTextScalar} = ''
end

BEGIN_MARK = '<!-- BEGIN generated by estimates/model_summary.m -->';
END_MARK   = '<!-- END generated -->';

infl = read_series(fullfile(char(csvdir), 'trend_inflation.csv'));
gap  = read_series(fullfile(char(csvdir), 'output_gap.csv'));
rows = [summarize(infl, "trend_inflation"); summarize(gap, "output_gap")];

if isempty(char(docfile))
    return
end

block = markdown(infl, rows, char(csvdir));
doc = fileread(char(docfile));
i = strfind(doc, BEGIN_MARK);
j = strfind(doc, END_MARK);
if ~(isscalar(i) && isscalar(j) && j > i)
    error('uc:estimates:model_summary:noBlock', ...
        '%s must hold %s and then %s, once each. Found %d and %d.', ...
        char(docfile), BEGIN_MARK, END_MARK, numel(i), numel(j));
end

% One write of one string: a percent sign anywhere in the guide would be a
% format specifier to fprintf if the text were passed as the format.
out = [doc(1:i - 1), BEGIN_MARK, newline, newline, block, newline, END_MARK, ...
       doc(j + numel(END_MARK):end)];
fid = fopen(char(docfile), 'w');
if fid < 0
    error('uc:estimates:model_summary:cannotWrite', '%s could not be opened.', ...
        char(docfile));
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, out);
end


% ---------------------------------------------------------------------------
function s = read_series(f)
% One struct per model, holding the dates and the three columns a table needs.
if ~isfile(f)
    error('uc:estimates:model_summary:noFile', '%s does not exist.', f);
end
t = readtable(f, 'TextType', 'string');
if ~isdatetime(t.date), t.date = datetime(t.date); end

s = struct('model', {}, 'dates', {}, 'mean', {}, 'p05', {}, 'p95', {});
for m = reshape(unique(t.model), 1, [])
    sel = t.model == m;
    d = unique(t.date(sel));
    s(end+1) = struct('model', m, 'dates', sort(d), ...  %#ok<AGROW>
        'mean', column(t, sel, "mean", d), ...
        'p05',  column(t, sel, "p05",  d), ...
        'p95',  column(t, sel, "p95",  d));
end
end


function v = column(t, sel, measure, dates)
% One measure of one model, on the model's own dates, in date order.
rows = t(sel & t.measure == measure, :);
[~, order] = ismember(sort(dates), rows.date);
v = nan(numel(dates), 1);
v(order > 0) = rows.value(order(order > 0));
end


function out = summarize(s, series)
out = table('Size', [numel(s) 9], ...
    'VariableTypes', {'string','string','string','double','double','double','double','double','string'}, ...
    'VariableNames', {'series','model','last_quarter','last_mean','band','sd_change','q2020','deepest','deepest_quarter'});
for k = 1:numel(s)
    m = s(k).mean;
    out.series(k) = series;
    out.model(k) = s(k).model;
    out.last_quarter(k) = qlabel(s(k).dates(end));
    out.last_mean(k) = m(end);
    out.band(k) = s(k).p95(end) - s(k).p05(end);
    out.sd_change(k) = std(diff(m), 1);
    out.q2020(k) = at(s(k), datetime(2020, 4, 1));
    [lo, i] = min(m);
    out.deepest(k) = lo;
    out.deepest_quarter(k) = qlabel(s(k).dates(i));
end
out = sortrows(out, 'last_mean', 'descend');
end


function v = at(s, d)
i = find(s.dates == d, 1);
if isempty(i), v = NaN; else, v = s.mean(i); end
end


function block = markdown(infl, rows, csvdir)
% The generated section: what the release says, and nothing that outlives it.
lines = {};
lines{end+1} = stamp(csvdir);
lines{end+1} = '';

common = infl(1).dates;
for k = 2:numel(infl)
    common = intersect(common, infl(k).dates(~isnan(infl(k).mean)));
end
means = arrayfun(@(s) at(s, common(end)), infl);
lines{end+1} = sprintf(['At %s, the most recent quarter every trend inflation model covers, ' ...
    'the estimates run from %.2f to %.2f percent.'], qlabel(common(end)), min(means), max(means));
lines{end+1} = '';
lines{end+1} = 'Trend inflation, in annualized percent. The band is the width of the 90 percent credible';
lines{end+1} = 'interval at the model''s last quarter, and the last column is the standard deviation of the';
lines{end+1} = 'quarterly changes in the posterior mean over the whole sample.';
lines{end+1} = '';
lines{end+1} = '| Model | Last quarter | Posterior mean | Band width | SD of quarterly changes |';
lines{end+1} = '|---|---|---|---|---|';
ti = rows(rows.series == "trend_inflation", :);
for k = 1:height(ti)
    lines{end+1} = sprintf('| `%s` | %s | %.2f | %.2f | %.2f |', ...
        ti.model(k), ti.last_quarter(k), ti.last_mean(k), ti.band(k), ti.sd_change(k)); %#ok<AGROW>
end
lines{end+1} = '';
lines{end+1} = 'The output gap, in percent of trend output. The last column is the deepest gap each model';
lines{end+1} = 'estimates anywhere in the sample.';
lines{end+1} = '';
lines{end+1} = '| Model | Last quarter | Posterior mean | Band width | 2020Q2 | Deepest |';
lines{end+1} = '|---|---|---|---|---|---|';
og = rows(rows.series == "output_gap", :);
for k = 1:height(og)
    lines{end+1} = sprintf('| `%s` | %s | %.2f | %.2f | %.2f | %.2f (%s) |', ...
        og.model(k), og.last_quarter(k), og.last_mean(k), og.band(k), ...
        og.q2020(k), og.deepest(k), og.deepest_quarter(k)); %#ok<AGROW>
end
block = strjoin(lines, newline);
end


function s = stamp(csvdir)
% What the release called itself, from the metadata beside the CSVs.
f = fullfile(csvdir, 'metadata.json');
if isfile(f)
    m = jsondecode(fileread(f));
    s = sprintf('These numbers are from vintage %s, released %s.', ...
        m.vintage, extractBefore(string(m.generated_utc), 'T'));
else
    s = 'These numbers are from the release beside this file.';
end
end


function s = qlabel(d)
s = string(sprintf('%dQ%d', year(d), quarter(d)));
end
